import React from "react";
import type { Metadata } from "next";
import Link from "next/link";
import { ArrowRight } from "@phosphor-icons/react/dist/ssr";
import { Container } from "@/components/ui/Container";
import { PageHeader } from "@/components/ui/PageHeader";
import { Notice } from "@/components/ui/Notice";

export const metadata: Metadata = {
  title: "Disclaimer & Privacy Notice",
  description:
    "What this service is, what it is not, and how it handles your data. Nothing you enter leaves your browser.",
};

const privacyPoints = [
  {
    title: "Your date of birth is never sent anywhere",
    body: "The calculation runs entirely in your browser. Your date of birth is not transmitted to a server, written to a database, or sent to an analytics endpoint.",
  },
  {
    title: "No account, no contact details",
    body: "This service asks for no registration, no telephone number, no email address and no government identification number.",
  },
  {
    title: "No tracking",
    body: "The checker uses no advertising cookies, no marketing pixels and no fingerprinting scripts.",
  },
  {
    title: "Data Privacy Act of 2012",
    body: "By keeping no record of what you enter, the service complies with Republic Act No. 10173 by design rather than by policy.",
  },
];

export default function DisclaimerPage() {
  return (
    <>
      <PageHeader
        eyebrow="Legal"
        title="Disclaimer and privacy notice"
        intro="This service helps you understand the age rules for the 2026 elections. It has no official standing, and it keeps nothing about you."
        crumbs={[{ label: "Disclaimer" }]}
      />

      <section className="py-12 sm:py-16 lg:py-20 border-b border-line">
        <Container size="md">
          <article>
            <h2 className="font-display font-semibold text-ink-950 text-2xl sm:text-3xl">
              1. What this service is
            </h2>

            <blockquote className="mt-6 border-l-[3px] border-l-orange-500 bg-surface-subtle rounded-r px-6 py-5">
              <p className="text-base sm:text-lg text-ink-900 leading-relaxed italic">
                This website provides general election information and an age-based
                eligibility guide based on the information entered by the user. Results
                generated by this tool do not constitute a final determination of voter or
                candidate eligibility. Official COMELEC records, applicable laws, rules,
                regulations and resolutions shall prevail.
              </p>
            </blockquote>

            <div className="mt-6 space-y-4 text-sm sm:text-base text-ink-700 leading-relaxed prose-civic">
              <p>
                The age computations and qualification summaries on this site exist for
                public education, voter awareness and civic participation ahead of the
                synchronised Barangay and Sangguniang Kabataan Elections on 2 November 2026.
              </p>
              <p>
                No calculation, printed sheet or shared result from this tool creates a
                binding legal presumption. None of it replaces the evaluation of a
                certificate of candidacy, a hearing of the Election Registration Board, or a
                resolution of the COMELEC En Banc.
              </p>
            </div>
          </article>
        </Container>
      </section>

      <section className="py-12 sm:py-16 lg:py-20 bg-surface-subtle border-b border-line">
        <Container size="md">
          <h2 className="font-display font-semibold text-ink-950 text-2xl sm:text-3xl">
            2. What happens to your data
          </h2>
          <p className="mt-4 text-base text-ink-700 leading-relaxed prose-civic">
            Nothing. That is the whole policy, stated four ways.
          </p>

          <dl className="mt-8 border-t border-ink-950">
            {privacyPoints.map((point, i) => (
              <div key={point.title} className="py-6 border-b border-line flex gap-5">
                <span
                  className="font-display font-semibold text-ink-600 text-sm shrink-0 w-6 pt-0.5"
                  aria-hidden="true"
                >
                  {String(i + 1).padStart(2, "0")}
                </span>
                <div>
                  <dt className="font-display font-semibold text-ink-950 text-base">
                    {point.title}
                  </dt>
                  <dd className="mt-2 text-sm text-ink-700 leading-relaxed prose-civic">
                    {point.body}
                  </dd>
                </div>
              </div>
            ))}
          </dl>
        </Container>
      </section>

      <section className="py-12 sm:py-16 lg:py-20">
        <Container size="md">
          <h2 className="font-display font-semibold text-ink-950 text-2xl sm:text-3xl">
            3. Non-partisanship
          </h2>
          <p className="mt-4 text-sm sm:text-base text-ink-700 leading-relaxed prose-civic">
            This website exists for non-partisan voter education and youth civic
            participation in Himamaylan City. It does not endorse, support or oppose any
            candidate, party-list or electoral faction.
          </p>

          <Notice tone="warning" title="If a result looks wrong" className="mt-8">
            Contact the Office of the Election Officer. Do not rely on this service alone
            when deciding whether to register or to file a certificate of candidacy.
          </Notice>

          <div className="mt-10 pt-8 border-t border-line flex flex-col sm:flex-row items-start sm:items-center justify-between gap-5">
            <Link
              href="/references"
              className="inline-flex items-center gap-2 text-sm font-display font-semibold text-navy-700 hover:text-navy-800 group"
            >
              Review the governing laws
              <ArrowRight
                size={15}
                weight="bold"
                aria-hidden="true"
                className="group-hover:translate-x-0.5 transition-transform"
              />
            </Link>

            <Link
              href="/checker"
              className="inline-flex items-center gap-2.5 px-5 py-3 min-h-[48px] bg-navy-700 hover:bg-navy-800 text-white font-display font-semibold text-sm rounded transition-colors active:translate-y-px"
            >
              Check my eligibility
              <ArrowRight size={16} weight="bold" aria-hidden="true" />
            </Link>
          </div>
        </Container>
      </section>
    </>
  );
}
