import React from "react";
import type { Metadata } from "next";
import Link from "next/link";
import {
  ShieldWarning,
  Lock,
  EyeSlash,
  Scales,
  CaretRight,
  House,
  CheckCircle,
  FileText,
  ArrowRight,
  ShieldCheck,
} from "@phosphor-icons/react/dist/ssr";
import { Container } from "@/components/ui/Container";
import { Button } from "@/components/ui/Button";

export const metadata: Metadata = {
  title: "Disclaimer & Privacy Notice | Himamaylan City COMELEC",
  description:
    "Official legal disclaimer, privacy commitments, and data protection policies for the 2026 SK Age & Eligibility Checker web portal.",
};

export default function DisclaimerPage() {
  return (
    <div className="flex-1 flex flex-col font-sans bg-slate-50 min-h-screen">
      {/* Breadcrumb */}
      <div className="bg-white border-b border-slate-200/80 py-2.5 px-4 text-xs font-medium text-slate-500">
        <Container size="xl">
          <nav className="flex items-center gap-1.5" aria-label="Breadcrumb">
            <Link href="/" className="hover:text-comelec-blue-700 flex items-center gap-1 transition-colors text-slate-600 font-medium">
              <House size={16} aria-hidden="true" />
              <span>Home</span>
            </Link>
            <CaretRight size={16} aria-hidden="true" className="text-slate-400" />
            <span className="text-comelec-blue-950 font-semibold">Disclaimer &amp; Privacy Policy</span>
          </nav>
        </Container>
      </div>

      {/* Hero Header */}
      <section className="py-12 sm:py-16 bg-gradient-to-b from-comelec-blue-950 via-comelec-blue-900 to-slate-950 text-white border-b border-comelec-blue-800 relative overflow-hidden">
        <div className="absolute inset-0 civic-grid-pattern opacity-30 pointer-events-none" />
        <Container size="xl" className="relative z-10">
          <div className="max-w-3xl space-y-3">
            <span className="inline-flex items-center gap-2 px-3 py-1 rounded-full bg-white/10 text-comelec-gold-300 border border-white/15 text-xs font-semibold uppercase tracking-wider">
              <ShieldWarning size={16} weight="fill" aria-hidden="true" className="text-comelec-gold-400" />
              <span>Legal Notice &amp; Privacy Safeguards</span>
            </span>
            <h1 className="text-3xl md:text-4xl lg:text-5xl font-bold tracking-tight text-white leading-[1.15]">
              Official Disclaimer &amp; Privacy Notice
            </h1>
            <p className="text-sm sm:text-base text-blue-100/90 leading-relaxed font-normal">
              Transparent terms of use, legal boundaries, and privacy protection protocols governing the Himamaylan City COMELEC Civic Eligibility Checker.
            </p>
          </div>
        </Container>
      </section>

      {/* Content Area */}
      <div className="py-12 sm:py-16 flex-1">
        <Container size="xl">
          <div className="max-w-4xl mx-auto space-y-8">
            {/* SECTION 1: LEGAL DISCLAIMER */}
            <div className="p-8 sm:p-10 rounded-xl bg-white border border-amber-300 shadow-card space-y-5 relative overflow-hidden">
              <div className="flex items-center gap-2 text-amber-800 font-semibold text-xs uppercase tracking-wider bg-amber-50 px-3 py-1 rounded-full border border-amber-200 w-fit">
                <Scales size={16} weight="fill" aria-hidden="true" className="text-amber-600" />
                <span>Statutory Legal Disclaimer</span>
              </div>
              <h2 className="text-2xl sm:text-3xl font-semibold text-slate-900 tracking-tight">
                1. General Informational Nature of Tool
              </h2>
              <blockquote className="p-5 rounded-lg bg-amber-50/90 border-l-4 border-amber-500 text-slate-800 text-sm sm:text-base italic leading-relaxed shadow-sm font-normal">
                &ldquo;This website provides general election information and an age-based eligibility guide based on the information entered by the user. Results generated by this tool do not constitute a final determination of voter or candidate eligibility. Official COMELEC records, applicable laws, rules, regulations, and resolutions shall prevail.&rdquo;
              </blockquote>
              <div className="text-xs sm:text-sm text-slate-600 space-y-3 leading-relaxed font-normal">
                <p>
                  The age computations and qualification summaries presented across this civic portal are designed solely for public educational assistance, voter awareness, and civic participation guidance in preparation for the <strong>November 2, 2026 Synchronized Barangay and Sangguniang Kabataan Elections</strong>.
                </p>
                <p>
                  No calculation, printed slip, or shared result generated by this tool creates any binding legal presumption or replaces official certificate of candidacy evaluations, voter list hearings of the Election Registration Board (ERB), or COMELEC En Banc resolutions.
                </p>
              </div>
            </div>

            {/* SECTION 2: PRIVACY & DATA SAFEGUARDS */}
            <div className="p-8 sm:p-10 rounded-xl bg-white border border-slate-200 shadow-card space-y-6">
              <div className="flex items-center gap-2 text-comelec-blue-900 font-semibold text-xs uppercase tracking-wider bg-comelec-blue-50 px-3 py-1 rounded-full border border-comelec-blue-200 w-fit">
                <Lock size={16} weight="fill" aria-hidden="true" className="text-comelec-blue-700" />
                <span>Zero Data Collection Policy</span>
              </div>


              <div className="grid grid-cols-1 sm:grid-cols-2 gap-5">
                <div className="p-5 rounded-lg bg-slate-50 border border-slate-200 space-y-2">
                  <div className="flex items-center gap-2 text-slate-900 font-semibold text-sm">
                    <EyeSlash size={16} aria-hidden="true" className="text-comelec-blue-700" />
                    <span>No Storage of Birthdates</span>
                  </div>
                  <p className="text-xs text-slate-600 leading-relaxed font-normal">
                    Your date of birth is processed entirely locally within your web browser. It is never transmitted to any external server, database, or analytics endpoint.
                  </p>
                </div>

                <div className="p-5 rounded-lg bg-slate-50 border border-slate-200 space-y-2">
                  <div className="flex items-center gap-2 text-slate-900 font-semibold text-sm">
                    <Lock size={16} aria-hidden="true" className="text-comelec-blue-700" />
                    <span>No User Accounts Required</span>
                  </div>
                  <p className="text-xs text-slate-600 leading-relaxed font-normal">
                    No account registration, personal phone numbers, email addresses, or government identification numbers are ever requested or stored.
                  </p>
                </div>

                <div className="p-5 rounded-lg bg-slate-50 border border-slate-200 space-y-2">
                  <div className="flex items-center gap-2 text-slate-900 font-semibold text-sm">
                    <CheckCircle size={16} weight="fill" aria-hidden="true" className="text-emerald-600" />
                    <span>Zero Tracking Cookies</span>
                  </div>
                  <p className="text-xs text-slate-600 leading-relaxed font-normal">
                    The eligibility calculator does not use advertising cookies, marketing pixels, or commercial fingerprinting scripts.
                  </p>
                </div>

                <div className="p-5 rounded-lg bg-slate-50 border border-slate-200 space-y-2">
                  <div className="flex items-center gap-2 text-slate-900 font-semibold text-sm">
                    <ShieldCheck size={16} weight="fill" aria-hidden="true" className="text-comelec-gold-600" />
                    <span>Data Privacy Act of 2012</span>
                  </div>
                  <p className="text-xs text-slate-600 leading-relaxed font-normal">
                    In strict compliance with Republic Act No. 10173, civic privacy is preserved by ensuring zero persistence of sensitive personal data.
                  </p>
                </div>
              </div>
            </div>

            {/* SECTION 3: CIVIC INTEGRITY */}
            <div className="p-8 sm:p-10 rounded-xl bg-white border border-slate-200 shadow-card space-y-4">
              <h2 className="text-xl sm:text-2xl font-semibold text-slate-900">
                3. Civic Integrity &amp; Non-Partisan Commitment
              </h2>
              <p className="text-xs sm:text-sm text-slate-600 leading-relaxed font-normal">
                This website is dedicated solely to non-partisan voter education and youth civic participation in Himamaylan City. It does not endorse, support, or oppose any political candidate, party-list, or electoral faction.
              </p>
            </div>

            {/* Bottom Actions */}
            <div className="pt-4 flex flex-col sm:flex-row items-center justify-between gap-4 border-t border-slate-200">
              <Link href="/references" className="text-xs font-semibold text-comelec-blue-700 hover:underline flex items-center gap-1.5">
                <FileText size={16} aria-hidden="true" className="text-comelec-gold-500" />
                <span>Review Official Governing Laws &amp; Acts</span>
              </Link>
              <Link href="/checker">
                <Button variant="gold" size="md" rightIcon={<ArrowRight size={16} weight="bold" />}>
                  Check My Eligibility
                </Button>
              </Link>
            </div>
          </div>
        </Container>
      </div>
    </div>
  );
}
